### ISSUE TITLE
itsa package

### ISSUE THREAD

**Issue by SRW612** [opensafely-core/stata-docker#11]
I would like to request the itsa package to be added to the Stata docker. This package enables a range of interrupted time series analyses in a straightforward and efficient way with a range of useful postestimation commands and inbuilt plots. Alternative ways of running interrupted time series models require a much more manual and long-winded approach.

**Comment by alexwalkerepi** [comment]
I think this package is fine to add.

**Comment by SRW612** [comment]
Thanks Alex.
@bloodearnest , is that a convincing enough case to add the package?
